p8105_hw2_cc5604
================
Changshen Chen
2026-10-04

# Problem 1

## Loading necessary package

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## Reading and cleaning the designated file

``` r
sub_df = 
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |> 
  janitor::clean_names() |> 
  select(line, station_name, station_latitude, station_longitude, starts_with("route"), entry, vending, entrance_type, ada) |> 
  mutate(entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE))
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `entry = case_match(entry, "YES" ~ TRUE, "NO" ~ FALSE)`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

## Dataset description

After cleaning, the dataset contains line, station name, station
latitude / longitude, routes served, entry, vending, entrance type, and
ADA compliance information. For the cleaning steps, I first used
`clean_names()` function to convert the raw column names into
standardized strings. Then, I used the `select()` function to keep only
the variables of interest listed above. Lastly, I used the `mutate()`
function to convert the entry variable from character (YES vs NO) to a
logical variable. The resulting dataset now has 1868 rows and 19
columns. These data are not tidy because the route number served is
stored in the column names instead of in a single variable.

## Answering the questions

1)  There are 465 distinct stations.

2)  84 stations are ADA compliant.

3)  37.704918% of station entrances / exits without vending allow
    entrance.

## Reformatting the dataset

``` r
tidy_df = 
  sub_df |> 
  mutate(across(route1:route11, as.character)) |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    values_to = "route_name"
  )
```

## Answering the questions

1)  60 distinct stations serve the A train.
2)  Of the stations that serve the A train, 17 are ADA compliant.

# Problem 2

## Reading and cleaning the designated file

``` r
mr_df = 
  readxl::read_excel("data/202509 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", range = "A2:N709") |> 
  janitor::clean_names() |> 
  filter(!is.na(dumpster)) |>
  mutate(sports_balls = as.integer(round(sports_balls)))

prof_df = 
  readxl::read_excel("data/202509 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", range = "A2:M134") |> 
  janitor::clean_names() |> 
  filter(!is.na(dumpster))

gwy_df =
  readxl::read_excel("data/202509 Trash Wheel Collection Data.xlsx", sheet = "Gwynns Falls Trash Wheel", range = "A2:L351") |> 
  janitor::clean_names() |> 
  filter(!is.na(dumpster))
```

## Combining the datasets

``` r
mr_df = mutate(mr_df, trash_wheel = "Mr. Trash Wheel", year = as.numeric(year))
prof_df = mutate(prof_df, trash_wheel = "Professor Trash Wheel")
gwy_df = mutate(gwy_df, trash_wheel = "Gwynns Falls Trash Wheel")

trash_df = bind_rows(mr_df, prof_df, gwy_df)

trash_df
```

    ## # A tibble: 1,188 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,178 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

## Dataset description

The combined dataset contains information on dumpsters from Mr. Trash
Wheel, Professor Trash Wheel, and Gwynns Falls Trash Wheel with rows
that do not include dumpster-specific data omitted. The resulting
dataset has 1188 rows and 15 columns, which meaning there are 1188
observations and 15 variables. I added an extra variable named
`trash_wheel` to keep track of which Trash Wheel is which when binding
the three datasets together. The key variables include time information
such as `month` and `year`, trash amount information such as
`weight_tons` and `volume_cubic_yards`, and specific trash record
including `cigarette_butts`, `plastic_bottles`, and `plastic_bags`. Some
variables are not included in all wheels, for example `sports_balls` is
only available for Mr. Trash Wheel.

## Answering the questions

``` r
weight =
  trash_df|> 
  filter(trash_wheel == "Professor Trash Wheel") |> 
  pull(weight_tons) |> 
  sum()

cig = 
  trash_df |> 
  filter(trash_wheel == "Gwynns Falls Trash Wheel") |> 
  filter(month == "June") |> 
  filter(year == "2022") |> 
  pull(cigarette_butts) |> 
  sum()
```

For the available data, 282.26 tons of trash were collected by Professor
Trash Wheel. 1.812^{4} cigarette butts were collected by Gwynnda in June
of 2022.

# Problem 3

## Reading and cleaning the baseline file

``` r
baseline_df = 
  read_csv("data/data_mci/MCI_baseline.csv", skip = 1, na = c(".")) |> 
  janitor::clean_names()|>
  mutate(
    sex = case_match(
      sex, 
      1 ~ "male", 
      0 ~ "female"
      ),
    apoe4 = case_match(
      apoe4, 
      1 ~ "carrier", 
      0 ~ "non-carrier"
      )
  ) 
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): ID, Current Age, Sex, Education, apoe4, Age at onset
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
clean_baseline_df = 
  baseline_df |>
  filter(is.na(age_at_onset) | age_at_onset > current_age)

n_women = nrow(clean_baseline_df |> filter(sex == "female"))
n_women_carrier = nrow(clean_baseline_df |> filter(sex == "female", apoe4 == "carrier") )
women_prop = (n_women_carrier / n_women) *100
```

The dataset was imported using the `read_csv()` function. I used
`skip = 1` arugument to omit the non-data entry and capture the real
header. The `na = c(".")` argument is used because a missing age at
onset is written as a period. For the cleaning steps, I first used
`clean_names()` function to convert the raw column names into
standardized strings. Then, I used the `mutate()` function to convert
the sex and apoe4 variable from numeric to character labels adapted from
the data description row. Lastly, I used the `filter()` function to
remove participants who had MCI at baseline. The dataset contains
participant id, current age, sex, education, apoe4 carrier, and age at
onset informtion. 483 participants were recruited, 479 participants met
the stated inclusion criteria, and 93 developed MCI. The average
baseline age is 65.0286013. 30% of women in the study are APOE4
carriers.

## Reading and cleaning the amyloid file

``` r
amyloid_df = 
  read_csv("data/data_mci/mci_amyloid.csv", skip = 1, na = c("NA", "Na")) |> 
  janitor::clean_names() |>
  pivot_longer(
    baseline:time_8,
    names_to = "time",
    values_to = "biomarker_values"
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (6): Study ID, Baseline, Time 2, Time 4, Time 6, Time 8
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

For the amyloid data, I used `skip = 1` argument to omit the non-data
entry and capture the real header. The `na = c("NA", "Na")` argument is
used because the na values are represented by NA or Na in the raw
dataset. For the cleaning steps, I first used `clean_names()` function
to convert the raw column names into standardized strings. Then, I used
`pivot_longer()` to store the five time-related features in a single
variable with another column matching the biomarker values to the
corresponding time of visit. The cleaned dataset now has 2435 rows and 3
columns. It contains study id, time, and biomarker value information.

## Checking whether some participants appear in only the baseline or amyloid datasets

``` r
baseline_only_df = 
  clean_baseline_df |> 
  filter(!(id %in% amyloid_df$study_id))

amyloid_only_df = 
  amyloid_df |> 
  distinct(study_id) |> 
  filter(!(study_id %in% clean_baseline_df$id))
```

8 participants appear in only the baseline dataset, and 16 participants
appear in only the amyloid dataset.

## Combining and exporting the datasets

``` r
mci_df = 
  clean_baseline_df |> 
  filter(id %in% amyloid_df$study_id) |> 
  left_join(amyloid_df, by = join_by(id == study_id))

write_csv(mci_df, "data/mci_combined.csv")
```

The combined dataset retains only the 471 participants who appear in
both datasets. It has 2355 rows and 8 columns. It contains all variables
from baseline and amyloid datasets. Each row represents one participant
at one visit.
